### ISSUE TITLE
Make a link on account name, so I can right click and open it in a new tab.

### ISSUE THREAD

**Issue by abitmore** [steemit/steemit.com#100]
Current design is hard to use, based on `onclick` event?

**Comment by Someguy123** [comment]
This issue applies to many things, not just the username links.

For example I almost lost my post by trying to look at my other posts to cross-link, since I assumed my standard CMD-Click would open in a new tab.

**Comment by aaroncox** [comment]
Is it alright to just change this into a normal link, or is `browserHistory.push()` being used as a way to prevent extra page loads? Wondering if there's some reasoning as to why this just isn't a normal link.

**Comment by roadscape** [comment]
@aaroncox: since it's a single-page app and most (or all) of the required state is already loaded, it's used to show the new page instantly without extra http requests.

@Someguy123: please create a separate issue with more details if this is still a problem.

Author links are now cmd-clickable. If I missed any feel free to reopen this issue.

**Comment by valzav** [comment]
btw, if you right click on user's picture in the top-right corner of the screen and select Open in new tab - it will work as intended.
