### ISSUE TITLE
Slow scrolling of image heavy or long posts.

### ISSUE THREAD

**Issue by Transisto** [steemit/steemit.com#1076]
I'm not a big fan of the way the post open as a pop-up window on top of the list of posts.

I think this is the reason why :  
Scrolling is very slow ans choppy.
back button does not behave like it's supposed to.
Clicking by mistake on the left or right of the post close it.

What are the advantages of that ?

**Comment by TimCliff** [comment]
It used to open the posts in the same window, but the problem was that when you were done reading the post and went 'back', the list of posts would be in a different position. It was annoying to have to scroll up/down and find your position again. Now, when you 'X' out of a post, whatever list you were looking at (feed, trending, etc.) is in the same position that you left it.

**Comment by mcifani** [comment]
Thanks Transisto. Please look at Tim's answer for more clarity. Closing ticket.
