### ISSUE TITLE
Hiding NSFW images

### ISSUE THREAD

**Issue by arhag** [steemit/steemit.com#15]
I do not agree with using tags (such as `#nsfw`) to mark explicit content. I think that is mixing up their true functionality. I have outlined the solution that I prefer in [this post](https://steemit.com/steem-standards/@arhag/explicit-nsfw-standard) (please read through it if you haven't already), although that proposal will probably require some slight modifications now that categories are being depreciated in favor of tags (they are right?).

That all said. I think there is a need for dealing with NSFW content sooner rather than later. So until a better solution is formalized and implemented, I think you should modify steemit.com to not show post summaries of posts tagged `#nsfw` regardless of `net_rshares` and to mark such posts with a special NSFW label. Opening the posts would show the full content.

**Comment by steemed** [comment]
"nsfw" is in the streem category name. Why not hide all images ins "nsfw" categories?

**Comment by arhag** [comment]
I consider that a very hacky solution to rely on. I believe it should ultimately be the author of the post/comment that gets to determine whether semantically their content is nsfw or not. The system can provide sane defaults from heuristics like finding patterns in the top-level posts tags' names, or whether  their parent posts have marked their posts NSFW.

**Comment by roadscape** [comment]
RE: https://steemit.com/steem-standards/@arhag/explicit-nsfw-standard
I think this metadata field approach is ideal and most flexible. Any post not using this field properly should be downvoted for not following standards.

Suggestion from pharesim:

> {"explicit": [“nsfw”]}
> Other values could then be “nsfl” or an age rating "r16", “r18”

I also wonder if there is any need for ratings like PG, PG-13, R, or content warnings like: spoilers, profanity, graphic violence, etc. Examples: https://en.wikipedia.org/wiki/Wikipedia:Content_disclaimer

**Comment by steemed** [comment]
I agree with @roadscape that if there is an explicit semantic marking for nsfw content, it should be part of a more general content disclaimer standard.

**Comment by arhag** [comment]
So are you guys sticking with the nsfw hashtag as the long-term solution for dealing with explicit content on steemit.com?

**Comment by jcalfee** [comment]
Sorry, I had not seen this come up much.  I'll re-open and leave it alone.  I have no comment...

**Comment by roadscape** [comment]
Currently, the rules (on the GUI side) can be boiled down to: 
 - if you are browsing a tag with /nsfw/ in the name, nothing is hidden
 - otherwise, if the post's category matches /nsfw/, it is hidden

(I'm not sure what rules the backend uses when it comes to indexing tags. `nsfw`, `test`, and `spam` may be handled differently.)

This may not be ideal but it's simple and imo working quite effectively. We could use `json_metadata` to store more granular details; this will require adding customizable forms to the "Submit Post" page, as well as a settings pane to select which content you want to see/hide. It's not clear if the settings would be per-browser or if we would need to begin persisting this to a database on the server (or on-chain in user's json_metadata?)..

> So are you guys sticking with the nsfw hashtag as the long-term solution for dealing with explicit content on steemit.com?

Long-term, I'm sure we will have something more complicated :) 

----

*Does the current approach have any drawbacks that is holding back growth?*

**Comment by TimCliff** [comment]
Related discussion: https://github.com/steemit/steemit.com/issues/827

**Comment by roadscape** [comment]
Let's continue discussion in #827
