### ISSUE TITLE
Feature request: Send Messages to Users

### ISSUE THREAD

**Issue by KrNel** [steemit/steemit.com#183]
Hello,  thank you for your work.

I think a PM feature is extremely useful and greatly needed to improve the networking and functionality of users across this media platform. Having everything through the "Chat" section is not as effective. Having a way to contact people directly without it, like on Facebook and other places, is a highly valuable aspect of social media.

Thank you for your consideration. Take care. Peace.

@krnel

**Comment by roadscape** [comment]
We are waiting on the backend private message implementation. Currently users send a small transaction (e.g. $0.001) along with a public or encrypted message to another account as a workaround.

Are users more in need of a private/encrypted chat, or a 'convenient' website-integrated public chat?

**Comment by KrNel** [comment]
Ah I see what you mean by encrypted, since it's on the public blockchain. I guess that's why the rocketchat is on a separate section. l0ki was talking in his posts about implemented something similar to an encrypted chat. I guess it's better to wait and get PMs private ;) That's better than 'convenience'.

Thanks.

**Comment by roadscape** [comment]
Part of this project will be to figure out how to securely store all of a user's memo keys. Since memo keys can be rotated, **all** previous memo keys will need to be stored if old messages are to be accessible. It may be possible to encrypt them in a nested fashion and store them on the blockchain. Otherwise they will need to be stored client side (but then they are not portable).

Closing until backend implementation is complete.
