### ISSUE TITLE
Image server does not support bmp

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#187]
No bitmaps @roadscape ??  I know, who uses bitmaps!!  Well, it happened:

https://img1.steemit.com/0x0/http://weatherwars.info/wp-content/uploads/2016/08/EL-831-Marion-1976.bmp

**Comment by mcifani** [comment]
The bmp images seem to preview fine in the editor.  Is there an actual post not displaying it properly? 
<img width="866" alt="screen shot 2016-08-26 at 7 53 50 am" src="https://cloud.githubusercontent.com/assets/1158463/18009725/646840c4-6b62-11e6-8ce8-e19cea4f8663.png">

**Comment by jcalfee** [comment]
The image in the editor does not use the image server.

**Comment by mcifani** [comment]
Aw.  Yep seems the Regex isn't matching for bmp images for compiling.

**Comment by jcalfee** [comment]
related: https://github.com/steemit/steemit.com/issues/43

**Comment by roadscape** [comment]
BMP is not a web-friendly format, and it would be rarely used while still adding complexity to a process we want as streamlined as possible. 

MSPaint can save JPEGS & PNG's nowadays if I'm not mistaken.

**Comment by jcalfee** [comment]
You could respond with a permanent forward code and url to the original image.

**Comment by jcalfee** [comment]
http://stackoverflow.com/questions/3778347/is-it-ok-to-http-redirect-images

**Comment by roadscape** [comment]
We can't forward the original image URL because it's a security risk (It would probably also be blocked by CSP headers)

All images on steemit.com need to be served by a trusted & secured server, and all external images need to go through a SSL proxy capable of img validation/filtering. We *could* add BMP support but it's not cheap to do so, and it's not a common (or ideal) web format.
