### ISSUE TITLE
User Profile - loadMore functionality for "Comments" and "Recent Replies" tabs

### ISSUE THREAD

**Issue by KrNel** [steemit/steemit.com#232]
Hello,

This has been bothering me since I noticed it a few weeks ago.

The Feed page, the Blog page, the Replies page, all have an auto-scroll to update the content and increase the page length. But, the Comments page does not. Can this be corrected? I can't find old comments I did...

Also, the Comment page has your Blog posts listed, this should be corrected, since your Posts on your Blog, are not Comments.

Thank you! Peace.

**Comment by jcalfee** [comment]
Looks like both the comments and recent replies need scrolling added.

**Comment by roadscape** [comment]
**Recent Replies**

Looking at the code, it looks like `get_state @user/recent-replies` uses `get_replies_by_last_update` -- however, I can't get this method to work properly. It takes parent_author & permlink as arguments, but this doesn't make sense if we're paginating by reply_author. It works for the first page by passing "" for permlink, but for any other case it seems broken to me.
https://github.com/steemit/steem/blob/76592f04af4a46bce9e8ad2d84020f7ed2b258c0/libraries/app/database_api.cpp#L1013

**Recent Comments**

AFAICT, we will need an API call for this because get_state uses a custom method to pull in recent 'posts'. Also we should ask them to **remove top-level posts** from this tab.
