### ISSUE TITLE
Popup is not active  - Firefox Ubuntu 14.04

### ISSUE THREAD

**Issue by matthewniemerg** [steemit/steemit.com#296]
On an Ubuntu 14.04 machine with Firefox, when I click on a post to read it, the new UI pops up a window.  This window is not active and if I use my arrows or mouse to scroll the background page scrolls instead.  I have to click on the container that has popped up to make it active to be able to scroll.

**Comment by valzav** [comment]
@matthewniemerg thanks for the report - will try to get the fix out asap.

**Comment by jcalfee** [comment]
FF 47 and 48 on Ubuntu scroll ok for me.  I'll check the specific version when @matthewniemerg replies.

**Comment by valzav** [comment]
tested in FF 38 as well - works perfectly.

**Comment by jcalfee** [comment]
I did notice this bug to a lessor extent.  The window does seem to be 'not active' at first because Page UP and Down does not scroll the text.  Clicking on the already opened post causes no visual change but does enable the Page Up and Down..   However still scroll using the mouse without clicking first.

I'm not sure what would cause this.  I tried using a focus events but it did not help.

**Comment by valzav** [comment]
@jcalfee try it again, I've fixed this issue yesterday - now it focuses the posts after open

**Comment by matthewniemerg** [comment]
Fixed (at least for me)!
