### ISSUE TITLE
Reorganize the meta information in a post summary

### ISSUE THREAD

**Issue by aaroncox** [steemit/steemit.com#352]
A suggestion: move the "time/author" span in the post summary to be the last element in the row.

![image](https://cloud.githubusercontent.com/assets/677686/18889669/d885a5a0-84b2-11e6-9b99-7822d293a4d7.png)

The new order of the elements would be:

- Vote
- Reblog
- Votes
- Comments
- Date/Author

This will give the page flow itself an easier vertical visual pattern to follow, as all of the numbers will line up slightly better.

An example of this is when I'm looking through a list of posts to see where discussions are occurring. This is how your eyes have to scan the page:

![image](https://cloud.githubusercontent.com/assets/677686/18889844/9addf4cc-84b3-11e6-9260-6d48d2934b11.png)

**Comment by valzav** [comment]
This change will rebalance the weights to the right - this might not be looking good, also it will require to re-align elements for small screens (on phones).
Another argument against this change - this is very minor issue but will require a lot of development efforts to be implemented because it will require a lot of css changes.

**Comment by roadscape** [comment]
The relevant elements were already isolated from mobile, so it turned out to be a fairly minor change, here's what it looks like:
https://cloud.githubusercontent.com/assets/5168676/18892524/c5a52602-84d7-11e6-9074-dfee01fc836b.png

Something about it feels off, though. Maybe it would be better without the reblog:
https://cloud.githubusercontent.com/assets/5168676/18892555/e96c57b8-84d7-11e6-9755-a778f0dad494.png

I think it may require more adjustments to get the visual balance right. 
This experiment is on branch `352-footer-reorg`

**Comment by aaroncox** [comment]
I think it looks great. It's so much easier to consume the statistics of each post. 

I've seen a number of people argue that since the # of votes is irrelevant, that could even be removed or displayed somewhere else (payouts dropdown?). 

Then the order could be:

(Vote) $Payout | (Reblog) | (Comments) | [Time] by [Author] in [Tag]

**Comment by roadscape** [comment]
@aaroncox: having (Reblog) immediately after $Payout could break alignment because the button disappears once a post is archived. For now I'll submit this PR as-is..

**Comment by roadscape** [comment]
Changes are live
