### ISSUE TITLE
Add a Resteem Reason

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#395]
Give users 140 characters to say why they resteemed a blog post, which appears below where the 'resteemed by' text appears.

**Comment by sneak** [comment]
The resteeming notice at the top of the post already clutters the UI enough. :)

**Comment by jcalfee** [comment]
I like the idea..  It would add a lot of life to re-steeming.

I'm also in favor of separating out the blog and resteem feeds.   I agree with @sneak too but only because there is a lack of separation between blogs and resteems.  We should follow blogs and resteems or just one or the other.  Also having a separate blog and resteem tab is valuable.  Finally, we use curie a lot and pay for it as it is a valuable service, but resteems is a automated form of curie where our trusted users volunteer their services so this is resteems and resteem comments is complimentary to curation and friendly to shareholders..

This is a block-chain level feature however and would require a hard-fork.  I'm sure they will add eventually if the blockchain devs agree it makes since from the long term perspective.
