### ISSUE TITLE
Markup for HTML Etc Parsed Incorrectly In Certain Instances

### ISSUE THREAD

**Issue by taoteh1221** [steemit/steemit.com#44]
I have a tutorial post on creating a basic HTML page (linked below). When I originally created the post it displayed fine, but now the code sections are not being parsed as such in the Steemit.com GUI.

https://steemit.com/developing/@taoteh1221/introduction-to-the-basic-structure-of-an-html-web-page

**Comment by jcalfee** [comment]
Here is an <html> and multiple <head> tags.  The real cause of the issue is the <html> appearing for the first time somewhere in the middle of your post.  You really should not have html, head, meta, or title tags in the post, those are for web pages.

Is there any way you can clean these up?  That will keep your posts smaller under the hood and more compatible with various browsers and devices.

**Comment by taoteh1221** [comment]
@jcalfee Do you happen to have a current link to your official documentation on including markup code as code examples on the Steemit website in posts there? I had the link when I created the post, but I did not bookmark it. That would be the way to retain my HTML tutorial code and not have to remove any of it, correct?

**Comment by jcalfee** [comment]
>You really should not have html, head, meta, or title tags in the post

It is html causing the issue .. not markdown.

**Comment by taoteh1221** [comment]
@jcalfee Then where lies the feasibility of blogging on programming with code snippet examples, if you cannot display / designate markup as a code example with something like a [code] tag?

**Comment by roadscape** [comment]
@taoteh1221, there's 2 main issues here:

1) The <html> tag has special meaning on the platform and it was incorrectly matching your code examples. Your first code sample became the entire post, which was then stripped further.

2) The post combines HTML with Markdown with more (potentially unescaped) HTML. Have you tried a service such as https://stackedit.io/? I checked some of your writing and it's a bit broken in stackedit too. Particularly, in some cases, `<html>` needs to be `&lt;html&gt;`.

----

In regards to the first issue, the platform will now be more strict about how it matches our "special" `<html>` tags. It no longer chews your code samples and will leave them alone.

We were also stripping out all HTML comments, due to a markdown parser bug. Now, only the comment start/end tag is stripped out and the comment itself remains. Not ideal.. but less mysterious.

As far as I can tell, the issue is resolved on our end and now just comes down to fixing the syntax within the post. Feel free to file a new ticket if there are any further issues after the next release.

**Comment by taoteh1221** [comment]
@roadscape Great news. When the issue occurred, I did try editing using different code identifiers than what were recommended (command example identifiers when referring to single tags in sentences) thinking maybe it was that...then gave up when it seemed apparent it was a bug. Those may be throwing the errors you refer to, even though you fixed it on your end. I will try reformatting it tomorrow. Thanks again.

**Comment by taoteh1221** [comment]
@roadscape Ok, will wait awhile for this release, before reporting any issues after cleaning up my syntax identifiers.

**Comment by roadscape** [comment]
The latest changes are now live at https://test.steemit.com/ if you'd like to try it out before the release!

**Comment by taoteh1221** [comment]
Perfect, thanks again! :-)
