### ISSUE TITLE
votes icon on @user/posts url is confusing/misleading

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#442]
<img width="1154" alt="screen shot 2016-10-07 at 23 19 31" src="https://cloud.githubusercontent.com/assets/408977/19209995/92851254-8ce4-11e6-8d6a-f1eab1256eb5.png">

Turns out that little human head is actually "comments"! Should be an upvote chevron. All this time I thought it was views...

**Comment by mcifani** [comment]
@sneak Since you mentioned this item the post preview footer has changed(screenshot for reference).  I believe if we put another upvote/chevron in place of the human head it could be confusing with the actual upvote
<img width="787" alt="screen shot 2017-01-31 at 5 46 01 pm" src="https://cloud.githubusercontent.com/assets/1158463/22487964/9c84f36a-e7dd-11e6-9442-4da063dc27f5.png">
 button.  The newer double human head seems less confusing.

**Comment by sneak** [comment]
I think the actual upvote button and the upvote symbol should be visually distinct, and it should be obvious without labels/text which is which.  Perhaps the upvote button should be more button-like and with a blue chevron (that fills in when voted on), and the uncircled monochrome one could be for the count (making it clear it's not a button).

Come to think of it, the current upvote button does not look very buttony.
