### ISSUE TITLE
BUG: Power Up should not show memo

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#474]

**Comment by thecryptodrive** [comment]
Now we have a nuance, the memo is gone from the powerup, and if one does a powerup all looks normal like so:

![image](https://cloud.githubusercontent.com/assets/22358264/19397486/56e10816-9248-11e6-8499-0a5e6c2d8880.png)

Then if you happen to do a memo to the same person thereafter using 0.001 steem, the memo appears twice, once in the memo itself of the 0.001 steem and the attaches itself to the previous powerup transaction like below, so memo appears twice:

![image](https://cloud.githubusercontent.com/assets/22358264/19397534/8b79d210-9248-11e6-9d6b-334617c7db11.png)

Is it not possible to just have the memo feature of PowerUP's? I have to use a separate memo to tell people what the powerup was from in steemsports which in inefficient. Lucky I have a script though, but it lost connectivity to steem.ws half way in which is why I'm doing manual and finding these bugs.
