### ISSUE TITLE
Future Proof Steem Against Potential Quantum Computing Threat

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#492]
If the claims in this article are true that a quantum computer can figure out a private key from a public key in minutes, all crypto would be dead in the water. If Steem can somehow harden itself against this possibility ahead of time then we could be the last crypto standing and inherit all of the market cap available in crypto side-by-side with any others that may have hardened themselves ahead of time.

https://cointelegraph.com/news/bitcoins-final-obituary-quantum-computers-may-kill-future-of-money

**Comment by iamsmooth** [comment]
I'm not an expert on QC. Some people who know more than I do have told me it is around the corner, and others have said essentially never.

One thing we do have as a measure of 'hardening' is that even with QC, an attacker would not be able to access SP or savings, since the blockchain-enforced rules slowing down access to those are not dependent on cryptography. 

QC could be viewed as a form of 'key stealing' hack which is exactly what these features (especially savings and account recovery) were intended to defend against. Upon detection of such an "event", these features would allow time for devs and witnesses to implement a hard fork that freezes balances in place and allow more time to decide how proceed. 

I'm going to guess that this github issue isn't the best place to discuss a nebulous long-term threat though. Issues are best used for specific bugs or work items which can be reviewed and coded and 'resolved'. Also, the 'steemit.com' repo is for the web site not the blockchain. Probably best to close this

**Comment by thecryptodrive** [comment]
Thank you for the great insights Smooth, seems Steem is at an advantage over other digital assets who do not have time delays on their funds, that makes me feel a little at ease and possibly a good reason to hedge on Steem in case of such an event,

I will close this. Is there a better place where long-term issues can be posted and discussed, especially regarding the Steem blockchain?

**Comment by iamsmooth** [comment]
> Is there a better place where long-term issues can be posted and discussed, especially regarding the Steem blockchain?

Not that I know of. It is a gap in the ecosystem (neither the Steemit blogging platform itself nor github issues serve this role well), but one that many other than me seem to recognize as an important need.
