### ISSUE TITLE
Wallet pages invalid the APR from sbd_interest_rate

### ISSUE THREAD

**Issue by mcifani** [steemit/steemit.com#597]

**Comment by iamsmooth** [comment]
Why was this closed? The issue persists. 

Displaying the correct and current APR on the wallet page is economically important since it affects the willingness of users to hold SBD and is part of the mechanism by which SBD supply and value is kept in balance with USD.

I opened issue #602 before seeing this one.

**Comment by roadscape** [comment]
> blockchain shows
> 
> `"sbd_interest_rate": 1500`
> 
> wallet page shows
> 
> `currently collecting 10% APR`

**Comment by abitmore** [comment]
Perhaps related? https://github.com/steemit/steem/issues/547

**Comment by mcifani** [comment]
Yep, right now it's hard coded in(the sbd rate).  Refactoring it slightly to be dynamic from blockchain so we don't need to constantly update it.

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [597-wallet-pages-invalid](https://trello.com/c/DCMp257C/131-597-wallet-pages-invalid)

**Comment by mcifani** [comment]
New update pushed to get dynamic value/replace hardcode.
