### ISSUE TITLE
Remove Upvote button/Flag button/Resteem button from Posts List

### ISSUE THREAD

**Issue by sean0010** [steemit/steemit.com#619]
Don't let users press Upvote/Flag/Resteem buttons without reading. These should only be at the end of the full content.
Upvote count/Flag count/Resteem count should stay in Posts List

**Comment by TimCliff** [comment]
I am not in favor of this change. I know that the intentions are good, but most people who upvote content without reading it are using bots anyway. 

As a human user, this degrades my user experience. A lot of times I will want to upvote articles from people I follow, because I know they have a history of producing great content and I want to get my vote in before other people. If after reading the post I realize it was a mistake, I can remove my upvote - but this rarely if ever happens.

In my opinion we should keep the upvote button where it is.

**Comment by abitmore** [comment]
IMO the design that voting before others qualifies more rewards is flawed.

**Comment by TimCliff** [comment]
The curation formula is way beyond the scope of this issue :) If a change is going to be made to that, it would need to be done at the blockchain level. I doubt it will be changed at this point though.

The SteemSports posts are an example of why the current button locations are good. I already know I am going to upvote it, and I don't want to scroll all the way to the bottom of the post before I can click. I upvote first, then read later. I know this is what this change is trying to prevent, but I don't think that the change should be made.

**Comment by mcifani** [comment]
Thanks for the suggestion, a good thought to increase participation, although in our current scope this shouldn't be removed as Tim noted. 

Closing the ticket to tidy up/no actual bug.
