### ISSUE TITLE
Nesting stops at six

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/steemit.com#627]
What is the hold up with this?
Isn't it simple enough  to just continue one under the other after so many?

**Comment by thebitcoiner** [comment]
I believe I read somewhere it wasn't a technical issue of not being able to nest indefinitely but a display issue of how to keep indenting and indenting.

**Comment by pfunks** [comment]
Technical issue was the original reason, but that technical issue (parent comment/post gets cut of child comment rewards) has been forked away long long ago. That issue is partially out of the way. I think the length of the permlink is still lingering as an issue, but there can be workarounds using the JSON field of a comment.

**Comment by TimCliff** [comment]
It is being discussed/reviewed here:
https://github.com/steemit/steemit.com/issues/497

**Comment by FreeBornAngel** [comment]
Thank You!!

**Comment by sneak** [comment]
Closing this issue in favor of discussion at #497
