### ISSUE TITLE
Reputation Level 70 Display Bug

### ISSUE THREAD

**Issue by KrNel** [steemit/steemit.com#643]
Hello,

Just wanted to let you know of a bug. I just turned level 70, not 79 ;)

**Profile:**

![krnel-profile](https://cloud.githubusercontent.com/assets/308183/20396738/2ddd1932-acb5-11e6-95f7-1ab69b4db070.png)

**Comment:**

![krnel-comment](https://cloud.githubusercontent.com/assets/308183/20396745/3228f380-acb5-11e6-8f9b-56c0772b2dd0.png)

**Steemstats:**

![krnel-steemstats](https://cloud.githubusercontent.com/assets/308183/20398627/2091d7ac-acbc-11e6-9f68-85e5d84b6437.png)

Thanks for the fix. Peace.

**Comment by jcalfee** [comment]
@roadscape 
If I use `Math.log(rep) / Math.LN10` instead of ParsersAndFormatters.log10 I get the correct rep of 70.

The raw rep value is: 100050507064372
ParsersAndFormatters.js:log10 returns 15
Math.log(rep) / Math.LN10 returns 14.000219294018713

JavaScripts max safe int is 16 digits: 9007199254740992

Looks like Math.log(rep) is going to work even beyond the max safe int:

Math.log(9007199254740992) / Math.LN10 === 15.95...
Math.log(99007199254740992) / Math.LN10 === 16.99
Math.log(999007199254740992) / Math.LN10 === 17.999568617941037

This is using the exponential notation to estimate the Math.log.

**Comment by roadscape** [comment]
Testing the methods in `app/utils/ParsersAndFormatters.js`,

```
1. log10 of  99999999999999 is approx 13 + 0.9999565683801923 (log=3.9999565683801923)
2. log10 of 100000000000000 is approx 14 + 0.9999999999999996 (log=2.9999999999999996)
3. log10 of 100000000000001 is approx 14 + 0.9999999999999996 (log=2.9999999999999996)
4. log10 of 100099999999999 is approx 14 + 0.9999999999999996 (log=2.9999999999999996)
5. log10 of 100100000000000 is approx 14 + 0.00043407747931833995 (log=3.0004340774793183)
```

Cases 2-4 are returning the wrong value due to a floating pt bug:

```
> Math.log(1000)/Math.log(10)
< 2.9999999999999996
```

Adding something like 10^-8 to the result of the log operation should be enough to round up these edge cases

**Comment by roadscape** [comment]
Just saw your commit.. I was doing to mention the following change on `app/utils/ParsersAndFormatters.js:40` resolves the issue -- a cleaner fix imho

```
- const log = (Math.log(leadingDigits) / Math.log(10))
+ const log = (Math.log(leadingDigits) / Math.log(10)) + 0.00000001
```
