### ISSUE TITLE
vimeo urls do not auto-embed

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#673]
Example: https://steemit.com/help/@freebornangel/ok-that-one-didn-t-work

**Comment by FreeBornAngel** [comment]
UnicornRiot.Ninja doesn't come up, either,...but it is just a url.

**Comment by jcalfee** [comment]
Do you want me to look at this one @roadscape .  I'm thinking I could just wrap https://vimeo.com/192097629 in an iframe in the markdown viewer.  That would provide a work-around to "Vimeo embeds not working in editor.".

**Comment by roadscape** [comment]
@jcalfee pls do, though I figured the best place to implement this would be in HtmlReady, where it currently handles YouTube embeds. This way you could just drop a vimeo URL in the Editor knowing it will expand to an iframe upon posting.

**Comment by jcalfee** [comment]
The last commit is technically feature complete and works as good as youtube embedding..  Except it will be missing a preview image URL for post sharing to other platforms.  This is because the preview image requires a callback .

.. @roadscape fetching the preview url would turn HtmlReady into a async operation.  That is not a light thing to do.  I'm giving this some thought first.  This would be avoided if vimeo would standardize on a image preview url format.

fyi:   http://stackoverflow.com/questions/1361149/get-img-thumbnails-from-vimeo

**Comment by roadscape** [comment]
@jcalfee your commit works great, I made a small change to wrap the iframe in `videoWrapper` class for responsive sizing. Let's leave the preview image for later. (We could possibly delegate this task to the image server too.)

**Comment by jcalfee** [comment]
@roadscape I do not see your commit.

**Comment by roadscape** [comment]
@jcalfee  https://github.com/steemit/steemit.com/compare/673-vimeo-auto-embed
