### ISSUE TITLE
Issues with Initial Steem Power Giveaway

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#685]
From @nikflossus

>I'm having an issue with my promotional startup and I don't know who to ask. I was promised either 5 or 10 dollars worth of Steem when I signed up in late October. In actual fact I received only 10Steem worth $1.63. I decided to wait for the payment. Yesterday I persuaded my partner to join and her account began with 50Steem. It seems like my reward has not been paid. I've asked in a blog and on the chat channels but no one seems able to help and I can't find a way to contact Steemit directly. Could you please help?

**Comment by roadscape** [comment]
When this account was created 2016-10-24, it received a vested balance of 10 STEEM worth around $0.20 each. You can see the transaction here: https://steemd.com/tx/6d0320491f13ef4758cd633f94926bcb5c662503

The account is currently worth around $285.56 as seen here: https://steemit.com/@nikflossus/transfers

To withdraw you need to initiate a powerdown.

**Comment by nikflossus** [comment]
Hello.

I think you've misunderstood my problem. I don't want to power down. I was hoping to be paid the promised sign up bonus of SteemPower (either $5 or $10) which I was promised. This has never paid to me.

Thanks!

**Comment by jcalfee** [comment]
You have to power down to get those initial steem.  Since you passed the minimum it will let you power down now.  If it gives you more in the power down than you want, you can just power up the rest of it.

**Comment by nikflossus** [comment]
Are you sure? When I signed up I started with 10 SP. When my partner signed up recently she started with 50.

**Comment by jcalfee** [comment]
I believe @roadscape changed the banner to calculate the new account bonus so this should be more accurate now..  Initially this was being manually updated so it was probably inaccurate at times.

**Comment by nikflossus** [comment]
Ok I see. Am I likely to get the $5 or $10 dollars worth of Steem I was promised? I feel a little cheated.

**Comment by roadscape** [comment]
- The signup bonus display has been dynamic since Aug 16 (https://github.com/steemit/steemit.com/commit/b873e7e7e6182277733717d36f9dd3c6d1086490) and always rounded down
 - Account 'nikflossus' received 10 STEEM POWER upon account creation, as shown in this tx: https://steemd.com/tx/6d0320491f13ef4758cd633f94926bcb5c662503
 - You can withdraw from your current balance of $285.56 (which includes the initial 10 STEEM)

**Comment by nikflossus** [comment]
Yes but my issue is that when i signed up I was promised either $5 or $10 worth of Steem. I never received it. Instead I got $1.63 worth.

I have no interest in withdrawing. I'm simply asking for what was promised.

**Comment by valzav** [comment]
@nikflossus, the amount steemit.com was giving away on October 24th was 10 STEEM, not $10, later this has been increased to 50 STEEM due to STEEM's high inflation rate.

**Comment by nikflossus** [comment]
Not when I looked at the sign up page I'm afraid. Do you think I'm making it up?  Someone messed up.

**Comment by TimCliff** [comment]
@nikflossus - I have transfered $5 SBD into your account, so you will not feel cheated.
https://steemit.com/@nikflossus/transfers

A few points though:
- This is a beta website, so it is possible for there to be glitches like this. It is not anyone "cheating" you, it is just the website is not fully developed yet.
- The value is set by the witnesses, and is not something Steemit, Inc. controls.
- The problem was that the website was just showing a hardcoded value based on how much was being given out at the time. The price of STEEM and the amount the witnesses were giving had changed, so the website was not reflecting an accurate value.
- They are planning to (if they have not already) update the site so that the amount shown to new users shows the amount based on actual amount the signup will give given the current price of STEEM and what the witnesses have it set to.
- In my personal opinion you should not be focusing as much on how _you_ are impacted by small stuff like this. Most of us are here trying to make the site better so that it can be adopted by the mainstream community. (Ask not what Steem can do for you; Ask what you can do for Steem :)
- I _do_ get that something like this can ruffle feathers and make you feel cheated though, which is why I sent you the 5 SBD. Hopefully this is all cleared up now :)

**Comment by nikflossus** [comment]
Thank you Tim. And thank you for your points.
1. Yes I do see that. I didn't mean to put the blame on anyone in particular. I just felt 'fobbed off' and perhaps expressed it badly.
2. I see. I didn't know that.
3. Ok so it looks like there was a confusion. I do still think it's important for new users not to feel unhappy at the beginning.
4. That sounds much much better.
5. I think my irritation grew at the way my issue was misunderstood, but you make a fair point. However I am making a good effort to make Steem better with my blog posts, particularly with trying to work out a system to make Paypal easily exchangeable for Steem.
6. That's very kind. Thank you.
