### ISSUE TITLE
Asking Permission for Project

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#721]
Hi! 

I know you guys are pretty busy and have a lot of stuff on the drawing board.

TimCliff & bitcoiner recently created the welcome page via pull request. 

I would like to create a more gamified version of it where people are walked through the website, kind of like how Facebook does it, for new users and have them get their Free SP for completing the tutorial.

I talked with them and they are okay for us to use some of the information they've compiled.

Before we engage in this process, I wanted to make sure it was okay with the Steemit team.

**Comment by TimCliff** [comment]
From what @RenaudGagne described to me, they are looking to create an interactive onboarding process that will walk users through a tutorial, possibly including something along the lines of quests.

One thing that I think will be needed is to see a detailed proposal of what it will do. For example, step 1 it takes the user to a page that describes avatars, and guides them to pick an avatar. (Maybe this isn't the best 'step 1', but you get the point)

I would be interested to see what all the steps are, and how it would integrate into the site. For example, what happens if a user wants to skip a step? How will they be able to see their progress, and go back to complete things later?

Also, the implementation details of the 'free SP' is probably going to be a big deal. Where will the STEEM come from? It would need to be _in addition_ to the free SP that is given to create an account. Also, assuming you want Steemit to be paying for it, how would the STEEM actually get transferred into the user's account? (Out of everything you are thinking of doing, this part seems the least likely to 'fly')

**Comment by RenaudGagne** [comment]
I am currently working on a mock up of what it would look like graphically.

As for the tutorial reward, i was thinking that we could transfer the SP only when the tutorial is done...not before. It would be a great way to deter the creation of fake accounts for SP. 

As for the SP for completing other actions at the end of the tutorial (such as sharing or following us on Facebook) then it could be considered as part of the marketing budget of steemit since its peanuts compared to spending money on other advertsing avenues.

I am currently wondering about what would be the best way to fund this operation. Bounty + witness sponsoring? Im also eilling to put some donations from my own funds in there.

I am curious to know what @dan and @ned think of this proposal.

**Comment by TimCliff** [comment]
I am fairly sure that the blockchain will not allow the account to be created unless the account creation fee is paid first. So a reward for completing tasks would need to be in addition to the account creation fee, unless you would be having an account created locally on Steemit first and only creating an account on the blockchain after certain tasks had been completed. This is possible, but would be a pretty huge change (in my opinion). It would also limit the types of tasks you could have them complete, since most things (commenting, upvoting, etc) would need an actual account first.

Regarding funding, that would be something to handle outside of GitHub. Usually Steemit.chat and posts are the best options for this.

If you create a post with all the details, you might get Dan and Ned's attention. On the development side though, @sneak is probably the person that you want to get approval from. A pre-approval from the dev team is not a guarantee that they will accept the pull request, but it is good to at least know if they are on board with the idea before you put a large amount of work into it.

**Comment by mcifani** [comment]
My thoughts on the rewarding process would potentially be after account creation. As example  Reward milestones could be for:  1. Creating your first post,  2. Voting for X amount of posts, etc.  The badges could also be synced to these milestones/or alternatively a further extension of rep scores for more flare.

**Comment by aaroncox** [comment]
For the initial implementation (and as a suggestion to just "get it done"), I'd recommend leaving out the financial rewards components of the on-boarding tutorial. It's going to add a layer of complexity that arguably isn't required. For the growth of steemit overall - a nice introduction and tutorial for the end users (without rewards) would be incredibly beneficial.

**Comment by sneak** [comment]
We have a feature like this already on our roadmap. Thank you for your feedback.

**Comment by RenaudGagne** [comment]
@sneak the question is when, if its in 2 years then why not leave people who want to contribute to the open source project get on top of it?

**Comment by sneak** [comment]
We expect our platform and feature roadmap to be published by the end of the year.

**Comment by abitmore** [comment]
@RenaudGagne the title of this issue looks not good -- better if it's detailed feature related, although I don't like @sneak's reply which sounds like asking people (who want to help) to leave.

**Comment by sneak** [comment]
I don't want anyone to leave. We have received your message and will incorporate your feedback, and we thank you for sending it.  This forum is for tracking bugs in the existing steemit.com codebase, and I close issues that are not direct work items because that's what our team uses this bug tracker for.

Please send your feature requests and suggestions to me directly at sneak@steemit.com.

**Comment by abitmore** [comment]
I think it's OK to submit feature requests on Github, with this more people can join the discussion.

**Comment by sneak** [comment]
Please send feature requests to me directly at sneak@steemit.com, and leave the bug tracker for bugs.  We have an internal system for tracking future plans and features - github isn't it.

**Comment by abitmore** [comment]
Unless you want to make this project (steemit.com) private/closed.

**Comment by sneak** [comment]
We have no intention of making the project private or closed.

**Comment by RenaudGagne** [comment]
This is not a feature request! This is asking permission to contribute to an open source project. I had intentions to contribute my own money and raise fund in order to hire devs to do the grunt work and contribute my skills in marketing in the UI.

But I guess thats not welcomed. Fair enough.

**Comment by sneak** [comment]
It is, of course, welcomed. 

In this particular instance I don't want you to spend your money implementing a feature that would get replaced by our own version (that dovetails with other, as-yet-unannounced features) in a month or two and have that work and money be wasted.
