### ISSUE TITLE
welcome page must be copyedited for tone and endorsement disclaimer added

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#723]
welcome page copy added in #585 is informal and requires copyediting (e.g. `hard-drive`).

**Comment by sneak** [comment]
- promoted is missing for the moment, remove references to it

- "back up your password offline" isn't helpful, include instructions

- steemit.chat, peerhub, steem prentice, et c are not run by steemit and a clear indication of third-party-ness is necessary.

- consistent capitalization of steemit, steem, steem power, et c

- copyediting for tone/flow

**Comment by roadscape** [comment]
Can this be merged into the #768 effort?

**Comment by sneak** [comment]
already talked to Tim about it, he's going to work on a separate PR

**Comment by TimCliff** [comment]
Yes

**Comment by TimCliff** [comment]
For the capitalization of Steem, Steemit, etc. - I was told that it should be "Steem" unless it is specifically referring to the currency - in which case it should be "STEEM". It looks like everywhere in the welcome page is currently following this convention.. 

-Should we just change it to be "Steem" everywhere instead of STEEM/Steem? 
-Also, should 'Resteem' be "Resteem" or "ReSteem"?

**Comment by TimCliff** [comment]
For the "Third Party" disclaimer, my plan is to add this section at the bottom. Will this be good for this item, or would you like something different?

**Third Party References**

Peerhub, BlockTrades, Poloniex, Bittrex, Steemit Chat, and Steem Prentice are third party applications, and are not owned or maintained by Steemit, Inc. Their listing here does not constitute and endorsement or recommendation on behalf of Steemit, Inc. 

All of the links in the "Helpful Posts from Steemit Users" were created by our users and do not necessarily represent the views of Steemit, Inc. or it's management.

Please use these third party tools and content at your own risk.

**Comment by sneak** [comment]
*its management. 

Otherwise looks great! Ty!

**Comment by sneak** [comment]
style guide:

400 STEEM

Steem Blockchain

steemit.com

resteem

Steemit, Inc.

**Comment by sneak** [comment]
PS: promoted is back now

**Comment by TimCliff** [comment]
For the "_copyediting for formatting (part faq, part quickstart)_" changes

1.  For the "_Does it cost anything to post, comment, or upvote content?_" section, I plan to change it to:

**Cost to Participate**

It is free to post, comment, or upvote all content on Steemit.com. You might even get paid for it!

2. For the "_Followers/Feeds_" section, I plan to change it to:

**Followers and Feeds**

3. For the "_STEEM, Steem Power (SP), and Steem Dollars (SBD)_" section, I plan to change to:

**Digital Currencies**

STEEM, Steem Power and Steem Dollars are the three forms of digital currency used by the Steem blockchain.

More information on the three types of tokens can be found in the Steemit FAQ.

4. For the "_Cashing out / Spending SBD_" section, I plan to change the title to "Cashing out or Spending SBD"

5. For the "_Keep your password secure!_" section, I plan to change the title to "Password Security"

6. For the "_How much should you expect to make on Steemit?_" section, I plan to change it to:

**Earning on Steemit**

The best attitude to have is to expect to make nothing. Have fun. Get engaged. Make friends. If along the way you earn some SBD - great!

It is possible to earn thousands of dollars, but most authors who are doing this have put in a lot of time/work to contribute a lot to the community and build followings.

**Comment by pfunks** [comment]
Here are some changes that I would like to see made to the Welcome page:

"The details behind the curation reward calculation can be found in the Steem whitepaper[link]." remove sentence/link/reference to Steem whitepaper because it's too outdated and may cause confusion?

Authors also have the option to be paid 100% in Steem Power! **->** Authors also have the option to decline payout, or be paid in 100% Steem Power!  

"Check here often to see if anyone has responded to you." can be nixed now that there are notifications 

The higher the number, the better. **->** The higher the number, the more weighted votes an account has earned.

"The lowest possible reputation score is -25 and the highest possible is 75." @steemsports has a reputation of 76 so the upper bound isn't right. Is there an actual upper bound? I think this sentence is extraneous. "New users at a reputation of 25." would be sufficient. Could also add something about the reputation score increases slowing down by a factor of 10 for every level: 40, 50, 60, etc.

Your reputation will go up or down depending on your interactions with other users. **->** Your reputation will go up as you earn votes for your posts and comments, but can come down if they are flagged.

"You can exchange your STEEM and SBD for Bitcoin" **->** "bitcoin" style: bitcoin as a unit of currency is not capitalized.

same sentence, "on an exchange such as BlockTrades, Poloniex, Bittrex." needs an "and" inserted in the list.

"Usually posts that are just sharing material that can be found elsewhere on the Internet don't do very well." I'd remove this sentence entirely, it unnecessarily limits Steemit's scope.

Posting someone else's work as if it were your own is very frowned upon by the Steemit community. **->** Plagiarizing, that is posting someone else's work as if it were your own, is very frowned upon by the Steemit community.

Also, make sure that you are not violating any copyright laws if you are using someone else's material/images. +add "Limited, sourced material sharing is ok under fair use and fair dealing doctrines."

Treat your Steemit password like you would your bank password. Keep it safe and secure!

add this below: "Unless the password was recently changed and you possess the old password, **there is no password recovery for Steem accounts**. You are 100% responsible for having it backed up. This means secure digital and secured paper backups, off-site if possible. If you have one, storing it in safety deposit box is strongly recommended."

If along the way you earn some SBD - bonus! **->** If along the way you earn something - bonus!

Under "Backup your password", repeat/hammer in the importance

Unlike centralized web services, **Steem has no account password recovery**. You are entirely responsible for keeping your password and keeping it secure.

Save your master key and keep it somewhere safe.

It is strongly recommended that you store an offline copy of your password somewhere safe in case of a disk drive failure or other calamity. Consider digital and paper offline storage, and use a safe deposit box for best redundancy. If your account is valuable, treat it like a valuable.

Signup for Steemit Chat **->** Sign Up for Steemit Chat

A lot of users hang out here and chat when they are not posting/curating. **->** A lot of users hang out and chat when they are not posting or browsing Steemit.

There is a link to signup **->** There is a link to sign up

Your Steemit chat account is a separate account from your Steemit.com login. **->** Your Steemit chat account is a separate account from your Steem account.

Some groups allow you to share links, but others don't. **->** Some channels allow you to share links, but others don't.

and after that sentence, add(?) "For instance, #general is for discussion without link promotion, while #postpromotion is for promoting your Steemit posts."

Each group will have its rules posted in the "Info" section. **->** Each channel will have its rules posted in the "Info" section.

The tradition for new users is to create an "introduceyourself" post, **->** While not required, the tradition for new users is to create an "introduceyourself" post,

under Other Resources:
Steem Block Explorer **->** Steem Blockchain Explorer steemd.com[link]
and add:
Steem Blockchain Explorer steemdb.com[link]

under "Where to go for live help" (caps consistency btw?):

add: "Ask your general question in the #help[link] steemit.chat channel."

Steem Prentice is a group of people dedicated to helping new users find their way around Steemit! **->** Steemprentice is a group of people dedicated to helping new users find their way around Steemit.

and put the following sentence on the same line

You can find them in the steemprentice Steemit.Chat channel. **->** You can find them in the #steemprentice steemit.chat channel.

**Comment by TimCliff** [comment]
Thanks for all the suggestions @pfunks! I will work these in.

**Comment by TimCliff** [comment]
Can this be closed?

**Comment by sneak** [comment]
Looks like it, yup. Thank you!
