### ISSUE TITLE
nsfw post handling

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#827]
The backend will remove any restrictions on posts categorized as `nsfw`, so we'll need to audit/upgrade how we handle this content on the frontend.

**Comment by TimCliff** [comment]
There is some discussion on it here. One of the issues can probably be closed for duplicate.

https://github.com/steemit/steemit.com/issues/406

**Comment by roadscape** [comment]
Marking posts as `nsfw`
 - Currently we use a tag for this
 - Alternatively, have a checkbox on the submit story form which sets a value in json_metadata (not ideal for mvp, probably *still* needs nsfw tag for organization)

User settings
 - Simplest solution is to have a `show_nsfw` setting in user's json_metadata.
 - Alternatively, use localStorage -- as a per-browser setting.

Handling of `nsfw` posts
 - Currently, any `nsfw` post is hidden unless you are specifically browsing `nsfw` (with the exception of what seems to be a recent bug)
 - I propose we hide them everywhere, but let user know that content was filtered and give a chance to globally enable showing of this content (similar to how "show low value posts" works but sticky)

**Comment by TimCliff** [comment]
I like the idea of hiding it everywhere unless the user enables it globally via their settings.

One idea for presenting the posts would be to show a stub post saying the post is hidden due to nsfw, but it can be enabled via the settings.

It also might be good to ask the user to verify they are old enough to legally view nsfw before allowing them to enable the setting.

**Comment by arhag** [comment]
I prefer using a values in `json_metadata` used for this purpose (with opportunity to expand beyond a simple nsfw to finer levels of detail) rather than a tag. A tag should be meant only to help organize posts into different feeds. An `explicit` field in `json_metadata` can further decide whether a post in that feed should be filtered out of the feed or hidden in some minimized form in some way when displayed as part of the feed, and also how the post itself should be rendered (the thumbnail image could be hidden or images within the post can be click-to-reveal for example).

I'm not a fan of forcing any of these local display settings to be  ones that the user must broadcast to the public blockchain. So I am a fan of having the user settings be stored in localStorage (per browser). Perhaps later on it may make sense to store an encrypted version of some critical settings on the blockchain as a way of backing it up and syncing across different devices/browsers that the user logs into.

I don't want a black and white solution to handling the rendering and display of nsfw content. Some may want to filter nsfw completely from their feeds. Some may want to see them in their feed but with the thumbnail pic hidden. Some may want to see all the content and images when they click to open nsfw content; some may want the text to be shown when they open the post but keep the images click-to-reveal; and, some may want the entire nsfw discussion thread to be completely hidden unless you click a button to reveal it (so that they don't accidentally see nsfw content by following some link to a steemit.com page). Also, the way the user arrives at the page matters (it changes the context through which the post must be rendered). If I arrived at the page by clicking a link in my feed that was clearly marked NSFW, I may not have a problem with having all the content and images of the discussion thread be visible (in fact, I would be annoyed to have to click-to-reveal each image). But if I am simply arriving at the steemit.com page from some external link, I want the images in nsfw posts/comments to be click-to-reveal (and there can be another button on the page to reveal all images in the discussion thread as a shortcut).

**Comment by jcalfee** [comment]
Agreed, don't put the setting on the blockchain that is a can of worms unless encrypted.  Local storage is fine.  I suggest that (if easy to implement) use the current behaviour we have now (show on direct link but hide it everywhere else).  If the user turns it on then show it everywhere.  I would not try to address advertising, just get the very minimum change out first and see how that works.

**Comment by jcalfee** [comment]
If the community wants more visibility into the filtering, this is a small variation of @TimCliff's idea:
>... show a stub post saying the post is hidden due to nsfw, but it can be enabled via the settings.

If the user ends up on a direct NSFW link, show it like we do now but include a message like:
> This material was labeled not safe for work (nsfw).  You may [configure](url) how to handle this type of material.

That could be at the lower left of the screen like roadscapes draft message..  It can be show without warning, warn, never show..

If we want to tell users about this filter in the signup process that would probably be good too.

**Comment by roadscape** [comment]
We'll use local storage. Currently I have it saving the setting per browser/user, so that on a shared computer different accounts can have different prefs.

@arhag we will add more granularity using `json_metadata` in the future, but until we implement our own indexes, `nsfw` as a tag is the best way to both flag and organize this content.

I've implemented 3 options for nsfw content:
 - always hide
 - warn (default)
 - always show

Currently, this applies only to List pages. Going to a full post directly does not hide anything.

**Comment by knircky** [comment]
I think it is best if we are very restrictive on sign-up and don't even mention nsfw. Think about kids and moms signing up.

Adults can and will find the settings where they can switch on the nsfw content. I don't think we need to worry about people finding the way to switch in on.

People who want regular folks to find their nsfw post can post regular articles and link to their nsfw post.

I think it is also important to store these settings locally. I don't mind seeing nsfw content but I don't want to see it in public, I.e. at work. So I need different settings on my home of and my work device.

**Comment by roadscape** [comment]
Merged into develop.
