### ISSUE TITLE
Specific userpage (@steemsports) returning 500 server error

### ISSUE THREAD

**Issue by pfunks** [steemit/steemit.com#873]
As of now, https://steemit.com/@steemsports returns a 500 server error. @thecryptodrive has made a post on Steemit about this here: https://steemit.com/steemsports/@thecryptodrive/steemsports-blog-server-error-on-steemit-com-please-tell-me-if-you-are-getting-the-same

If the https://steemit.com/@steemsports/transfers page is visited, it works, and clicking the blog link from there will load the URL that originally gives a 500 server error. The page will also successfully load if the account link is clicked from one of its posts or comments.

**Comment by Netherdrake** [comment]
It is a very peculiar issue indeed. I'd be curious to know how did it break.

**Comment by jcalfee** [comment]
https://github.com/steemit/steemit.com/issues/874

**Comment by jcalfee** [comment]
```
SteemApi exec 0 get_state ( [ '/@steemsports' ] )
WARNING! ws connection wss://steemit.com/wspa closed:  Frame size of 3503887 bytes exceeds maximum accepted frame size
```

![image](https://cloud.githubusercontent.com/assets/204121/21295204/98d4c7c6-c515-11e6-8f8a-3420b4535876.png)

Just a guess, but this could be a very long set of voting history in steemsports' posts.  We might want to temporarily increase the frame size then look at why we have to pull back so much data.

**Comment by mcifani** [comment]
Just a thought:  Perhaps the issue is from not sending the data over multiple WS frames.

**Comment by jcalfee** [comment]
Because you can browse to @steemsports just fine, it tells me that the browser can pull this websocket frame from steemd  just fine ...  It is the w3c socket package used in the initial static page render (in nodejs) that is throwing the error.

https://www.npmjs.com/package/websocket#client-example-using-the-w3c-websocket-api

**Comment by jcalfee** [comment]
get_state /@steemsports returns a frame that is about 3.77MB.  I'm able to copy the frame and paste it into a fast text editor that has a word wrap.  It looks like a lot of content.  I believe get_state should probably return content summary instead of the full content while get_content can fill in the rest. 

This will fix the socket in the short run:

```
+++ b/shared/api_client/reconnecting-websocket.js
@@ -277,7 +277,7 @@
             }
 
             console.log('connecting to', surl);
-            ws = process.env.BROWSER ? new WebSocket(surl) : new WebSocket(surl, protocols || [], null, null, null, {maxReceivedFrameSize: 0x300000});
+            ws = process.env.BROWSER ? new WebSocket(surl) : new WebSocket(surl, protocols || [], null, null, null, {maxReceivedFrameSize: 0x600000});
             ws.binaryType = this.binaryType;
 
             if (self.debug || ReconnectingWebSocket.debugAll) {
```
