### ISSUE TITLE
Some pending conversions are not appearing correctly on wallet page

### ISSUE THREAD

**Issue by pfunks** [steemit/steemit.com#896]
[@ats-david](https://steemit.com/@ats-david/transfers) pointed out that his wallet page does not give him an indicator of his pending SBD conversion. This is his current conversion, not displayed on Steemit: 

"id": 11100,
    "owner": "ats-david",
    "requestid": 1482175923,
    "amount": "66.466 SBD",
    "conversion_date": "2016-12-23T07:32:15"

[@mughat](https://steemit.com/@mughat/transfers), who has no pending conversions, has a wallet page that has his past conversions listed.

**Comment by roadscape** [comment]
Also, @steemit2 has no active conversions, yet an old one is shown:

STEEM DOLLARS
$48,729.915
(+$100,000.000 in conversion)

**Comment by roadscape** [comment]
@steemit2 shows a very old conversion in `other_history`:

```
get_state "@steemit2/transfers"
....
        "other_history": [[
          2312,{
            "trx_id": "348a42127bf00133a0af6bfe2627bd4c0a78a89f",
            "block": 4940929,
            "trx_in_block": 0,
            "op_in_trx": 0,
            "virtual_op": 0,
            "timestamp": "2016-09-13T18:13:48",
            "op": [
              "convert",{
                "owner": "steemit2",
                "requestid": 1473790427,
                "amount": "100000.000 SBD"
              }
            ]
          }
        ]
      ],
```

While @ats-david does not show a recent conversion in `other_history`:

```
get_state "@ats-david/transfers"
....
        "other_history": [],
```

Looking at where `other_history` is [populated](https://github.com/steemit/steem/blob/dea5268112d9723c4de0143321c430deabdb93b4/libraries/app/database_api.cpp#L1912), I see this issue is adjacent to #375, with a backend workaround suggested at https://github.com/steemit/steem/issues/521

**Comment by roadscape** [comment]
Half of this issue *is* on the UI side. Old conversions are currently not being filtered out.

**Comment by roadscape** [comment]
Fixed in https://github.com/steemit/steemit.com/pull/899
