### ISSUE TITLE
Instead of flag add negative scale to upvote slider

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#938]

**Comment by pfunks** [comment]
How will the slider behave after a previous vote? If a previous vote was negative, defaulting to the same negative value the next time the vote button is pressed could result in accidental downvotes. At the same time, having the slider at the same value for previous upvotes is convenient most of the time, as click-click to vote is a simpler and quicker process than click-slide-click.

**Comment by valzav** [comment]
@pfunks yes, I think it just shouldn't remember negative vote values.

**Comment by TimCliff** [comment]
Not sure if we want to handle it this way, but one idea is to not allow a downvote through the UI until they reach 1 MV. Another possibility - two buttons (upvote/downvote).

**Comment by sneak** [comment]
What problem is this trying to solve?

**Comment by jcalfee** [comment]
Fabien gave me this screen shot from busy.org:
![image](https://cloud.githubusercontent.com/assets/204121/21684840/e51f2208-d324-11e6-97e2-78ccac5a9571.png)

> IMO it makes more sense to not call it a Flag and incentive downvote

We can probably accomplish the same thing with a new icon and a little re-wording.

**Comment by valzav** [comment]
@sneak, Dan wants to make downvotes to be used more often, they should be seen as opinion expressed by users, pretty same as upvotes.

@jcalfee I like this idea, hope we would be able to adopt this.

**Comment by sneak** [comment]
Invoking Dan's name doesn't mean we short-circuit our process and plan. That's not on our roadmap and it's not on the critical path to user growth. It's a non-problem right now.

Maybe it becomes a problem in the future when we see more shitposting or trolling, but until that happens, we should be putting 100% of our effort into our growth initiatives. There will be plenty of time to tune the reputation and downvoting system later - but only if we ship the things in the roadmap *first*.

**Comment by CraigWilliams** [comment]
I think down voting/ flagging is ridiculous. If you don't like what someone is posting, don't _upvote_ it. That is the response to not liking something. 

Don't throw bricks through the window of the store you disagree with what they are selling just don't purchase anything from them. If the majority of people agree with you then the store goes out of business. 

Elicit content is market as such and all other content is **opinion** which should not be hindered upon. Honestly, people are too biased to objectively mark content as inappropriate. By which standard are we judging? Is this not similar to book burning? Down vote a persons content enough and they are not seen. And, limiting the down vote option to people with a certain vest is irrelevant. Just because someone has money does not make them objective and should certainly not give them the power to squash another persons ability to post content.

Can someone please tell me why there is an option to limit another persons ability to express themselves? Why is this even a subject on this forum?

**Comment by TimCliff** [comment]
The ability to downvote posts is built into the blockchain, and the whitepaper lists 'payout too high' (which is subjective) as a valid reason to downvote. From a UI perspective, switching the 'flag' to a downvote slider would be more in line with the way the functionality is designed and implemented at the blockchain level. There is a valid discussion to be had about the appropriateness and etiquette of flagging, but it is probably best had outside of GitHub.

**Comment by valzav** [comment]
Agree with @sneak, so I'm closing this issue..

**Comment by sneak** [comment]
> Can someone please tell me why there is an option to limit another persons ability to express themselves?

FWIW, there isn't. The blockchain is append-only. Even flagging is just *additional* speech. Flag away on whatever subjective grounds you like - but everyone reaps what they sow. This community has a memory. :)
