### ISSUE TITLE
reduce post payout options to only two: 1) decline payout 2) SP only payout (default)

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#961]

**Comment by pfunks** [comment]
Can you clarify? Do you mean you want to change steemit.com to not offer a liquid token post payout option?

**Comment by valzav** [comment]
@pfunks: correct

**Comment by pfunks** [comment]
Why?

**Comment by valzav** [comment]
There are several considerations (according to Dan):

1. Less debt for the system.
2. SP takes longer to hit the market than SBD so theoretically it should be less downward pressure on STEEM.
2. Facilitates more frequent visits to the website to power down and withdraw
3. Dollars might be more difficult to account in terms of taxes.

Please note this is UI only change and subject for discussion.

**Comment by pfunks** [comment]
re: 1. While true, a debtless system means no SBD and therefore no easily understandable token of value for the every day people Steem was originally meant to attract.

re: 2. It will probably end up being more downward pressure because people will instead be forced on a powering down-track, selling the *other half* of their posting rewards at the same time.  

Many users take pride in their SP and wouldn't want to have to power it down. This also erodes the original concept and selling point of stakeholder participants, where people are more likely to treat half of their posting rewards as their reputation, their sweat equity into Steem by way of Steemit.

re: 3. There are better ways of user retention than selling out the existing and good concept of 50/50 liquid/SP rewards and encouraging divestment from the system.

re: 4. Users can choose 100% SP if that's a concern. No change is needed.

Apart from these points, I would expect extreme backlash against the removal of the liquid post reward option on steemit.com from many if not most Steemit users. It has a high potential to reduce creative engagement with the Steem platform.

**Comment by iamsmooth** [comment]
Reason #1. Is a very short-sighted approach. The debt level is high now, but what happens when the SBD supply becomes low enough to be no concern but utility is impaired because no more is being created? Today's solution becomes tommorow's problem. If anything, this should be sensitive to debt load (say above 2% debt ratio, which means it would take the place of the mixed STEEM/SBD payouts that happen now). 

Also, putting this in the UI means that people using non-standard tools/bots/auto-reposting services, etc. will have an extra option that ordinary web UI users don't. That seems like a recipe for further dissatisfaction and resentment.

**Comment by TimCliff** [comment]
I tend to agree with the comments above..

I did try to take a step back though and think if we were to design the system/site from scratch - what would the 'best' way be. In that context, a 100% SP payout wouldn't be _that_ bad of an idea. There are pros and cons on each side. 

If we go down that path though, then it does more or less eliminate the purpose/use of SBD. Even if there was a way to produce SBD, what is the purpose of setting up a marketplace for user rewards, if users have to exchange STEEM to SBD in order to use it? In the current world (assuming USD _doesn't_ crash and burn) - users might as well exchange their STEEM for USD and go buy something at anywhere fiat is accepted. I'm not saying that as a reason _not_ to go down that path - but if we did, we might as well eliminate SBD (IMO).

One of the bigger reasons against it IMO though is that with the ability to use liquid rewards via other posting interfaces - it will likely just discourage users from using Steemit.com, and push them to other sites instead.

As far as the debt, it is not as significant of a change but one idea that might help would be a "50% STEEM / 50% SP" payout option. We already go to this when the debt level is too high, so why not give users the option to receive payouts this way regardless of the debt level?

**Comment by FreeBornAngel** [comment]
Keep the sbd, but why does it have to be a debt instrument?
Does steemit have to make up the difference if the price rises, or does it come from buyers in the market?

I liked a 10% a month powerdown, and the high inflation.
I agree that it was unsustainable, but it sure looked nice watching those numbers change as quick as I could refresh.
Inflation doesn't have any impact until that steem is traded for something.
If 'we' hold enough we can increase the value, but good luck getting the masses to go for that.

Using a forced power up is only temporary, at best.
If the underlying value isn't there the project fails.
I think that value is in the freedom that the platform provides, not in the restrictions on capital flight.

**Comment by iamsmooth** [comment]
> Keep the sbd, but why does it have to be a debt instrument?

Calling it debt is more of a metaphor. It is debt-like in increasing leverage because it requires more STEEM to pay out when the STEEM price declines and less when the STEEM price rises.

**Comment by FreeBornAngel** [comment]
Ok, but who incurs that?
The market, no?

Has the drop in inflation caused fewer power ups?
Anything that encourages folks to stop selling is gonna benefit all holders.

**Comment by samupaha** [comment]
I also think that this could cause even more sell pressure when more users start powering down.

Instead of thinking how to stop the price falling down we should be thinking how we can make steem more valuable so that people will buy it more.

Currently steem is pretty much only an investment. Not much places where people can use actually it. Users who earn rewards will sell them for other cryptocurrencies and fiat-money so the value is constantly flowing out from the system.

Things like marketplace could be great long-term solutions.

**Comment by steemonthewayout** [comment]
If you want to give the appearance of a Ponzi by locking 100% of the author rewards by all means. Please remember that perception goes a long way.

**Comment by lafona** [comment]
I think the distribution aspect is what sets sbd apart from any other stable coin. This change would remove that. That being said, I think this could be helpful as a temporary action to help reduce the sbd debt from the original run up, but the same thing could be accomplished at the blockchain level as smooth suggested.

**Comment by samupaha** [comment]
Maybe we could first use softer ways to accomplish this.

I suggest that steemitblog, dan and/or ned publish a post where they explain the situation and ask that users would take the reward as SP until the debt ratio is better.

There could be an indicator in the post editor that would tell when the debt ratio is not optimal and encourage users to take reward as SP. "Power Up 100%" could be the default choice.

**Comment by RenaudGagne** [comment]
This is a terrible idea from a user perspective.

**Comment by valzav** [comment]
Thanks for your input guys
